### ISSUE TITLE
Example request :)

### ISSUE THREAD

**Issue by UnrulyNatives** [matiit/wkop#14]
I'd be extremely happy to see an example which does this: 

1) checking if an URL is submitted as "wykop" and then returning the Wykop.pl's URL or null

Thx

**Comment by matiit** [comment]
> checking if an URL is submitted as "wykop"

What do you mean by that?

**Comment by UnrulyNatives** [comment]
Thank you for your attention.

Consider this scenario: 

1) in my app I add a link to a news in say... youtube.com
Example:
http://www.youtube.com/watch?v=ZXM7fTXt3_U

2) Now I want to check if in the wykop.pl someone already added a 'wykop with that link. 

and... yes! Someone already submitted this "wykop", which has URL
http://www.wykop.pl/link/2526767/marian-kowalski-cieta-riposta-na-glupie-pytanie-prowadzacej-program/

My goal: 
I want to submit the youtube.com link to Wykp.pl's API and get in return either NULL or the link to 'wykop', which I want to add as 'related discussion' model pivoted to my Event model in my app (step 1 above)

Thx

**Comment by matiit** [comment]
To be honest, Wykop API documentation doesn't say about any method which would allow to perform this kind of query.

http://www.wykop.pl/dla-programistow/dokumentacja

There's only method to add new link, but it doesn't return "possible duplicates". 
I might be wrong though, I will examine this on weekend.

**Comment by matiit** [comment]
Yeah, looks like there's no api method to call for that
