### ISSUE TITLE
Base href linków

### ISSUE THREAD

**Issue by kalinowski5** [matiit/wkop#6]
Witam!
Czy istnieje jakaś opcja, żeby tworzone linki do tagów były absoultne, a nie relatywne?
Np. `<a href="http://www.wykop.pl/tag/medycyna">medycyna</a>` zamiast obecnego `<a href="#medycyna">medycyna</a>`.

Pozdrawiam

**Comment by matiit** [comment]
Chodzi Ci o linki zwracane przez API? Nie mam na to wpływu :) 

Chyba, że chodzi o coś innego, to napisz dokładniej i mogę dodać jakiś parametr.

**Comment by kalinowski5** [comment]
> Chodzi Ci o linki zwracane przez API? Nie mam na to wpływu :)
aaa, faktycznie
Wydawało mi się, że w Twoim kodzie jest jakiś parser, ale teraz widzę, że to API zwraca takie linki...
